name: Build LaTeX Document

on:
  push:
    paths:
      - content/CV/**
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git Repository
        uses: actions/checkout@v2
      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: content/CV/CV.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: CV.pdf